---
- name: Install K8S master services
  hosts: aws
  become: true
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - raw: apt-get install -y python2.7 python-simplejson
      become: true
      become_method: sudo

    - name: K8S | Install Master | Initialize K8S with kubeadm
      shell: kubeadm reset
      become: true
      become_method: sudo  

    - name: K8S | Install Master | Initialize K8S with kubeadm
      shell: kubeadm init --pod-network-cidr=192.168.10.0/24
      become: true
      become_method: sudo

    - name: K8S | Install Master | Create .kube directory
      file:
        path: /home/ubuntu/.kube
        state: directory
      become: true
      become_user: ubuntu

    - name: K8S | Install Master | Copy admin.conf file to /.kube/config
      copy:
        src: /etc/kubernetes/admin.conf
        dest: /home/ubuntu/.kube/config
        remote_src: yes
      become: true
      become_method: sudo

    - name: K8S | Install Master | Change ownership on /.kube/config
      file:
        path: "/home/ubuntu/.kube/config"
        owner: ubuntu
        group: ubuntu
      become: true
      become_method: sudo

    - name: K8S | Install Master | Install pod network
      shell: "kubectl apply -f https://docs.projectcalico.org/v3.0/getting-started/kubernetes/installation/hosted/kubeadm/1.7/calico.yaml"
      become: true
      become_user: ubuntu

